apiVersion: apps/v1
kind: Deployment
metadata:
  name: aks-petstoreproductservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aks-petstoreproductservice
  template:
    metadata:
      labels:
        app: aks-petstoreproductservice
    spec:
      nodeSelector:
        "kubernetes.io/os": linux
        agentpool: nodepool1
      containers:
      - name: petstoreproductservice
        image: petstorecrs.azurecr.io/petstoreproductservice:latest
        resources:
          requests:
            cpu: 250m
            memory: 1Gi
          limits:
            cpu: 500m
            memory: 2Gi
        ports:
        - containerPort: 8080
        env:
          - name: PETSTOREPRODUCTSERVICE_SERVER_PORT
            value: "80"
          # - name: spring.config.name
          #   value: application_with_everything_enabled
          # - name: APPLICATIONINSIGHTS_CONNECTION_STRING
          #   valueFrom:
          #     secretKeyRef:
          #       name: aisecretkey
          #       key: secret
        env:
        - name: PETSTORESERVICES_AI_INSTRUMENTATION_KEY
          value: "98dc39f9-f212-4d02-90db-9fa5d2cc3168"
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: aks-petstoreproductservice-hpa
spec:
  maxReplicas: 4 # define max replica count
  minReplicas: 1  # define min replica count
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: aks-petstoreproductservice
  targetCPUUtilizationPercentage: 80 # target CPU utilization
